---

version: '3'

services:
  fakeserver:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - loadbalancer
    networks:
      fakenetwork:
         ipv4_address: 10.0.0.8
    ports:
      - "3000:3000"
  loadbalancer:
    image: nginx
    ports:
      - "80"
      - "443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./cert.pem:/etc/ssl/certs/cert.pem
      - ./privatekey.pem:/etc/ssl/private/privatekey.pem
    networks:
      fakenetwork:
        ipv4_address: 10.0.0.2
networks:
  fakenetwork:
    ipam:
      config:
        - subnet: 10.0.0.0/8
#        gateway: 10.0.0.1

